### ISSUE TITLE
Messages to/from a newly created account are not decrypted (or not decrypted properly)

### ISSUE THREAD

**Issue by ghost** [Ben-Ortiz/cs419_group_project#4]
Conversations are decrypted successfully when both users log in directly. But if one user has just created an account, then messages to/from them will not be decrypted unless they logout and login again using the now-existing account.

![image](https://user-images.githubusercontent.com/95466954/144700788-0fa341de-d784-4124-baf0-8efee4cad960.png)

Steps to reproduce:
1. Start the server
2. Start a user instance, and create a new account
3. Start another user instance, and either login to an existing account or create a new account
4. Message between those users

**Comment by jayko8899** [comment]
Closing this issue as it has already been mentioned and patched

**Comment by ghost** [comment]
Ah, I didn't notice #2 where this was mentioned since it was closed, my bad. 

I don't believe we're intended to make changes to our programs now that the submission deadline has passed though, so Ling's bug report should probably still be open/valid.

**Comment by symxmyz233** [comment]
Sorry, **someone has found it** ahead of you.
